name: 1-Checkout-Build-Artifact

on:
  workflow_dispatch:
  schedule:
    # Runs "Everyday at 7:05" (see https://crontab.guru)
    - cron: '5 7 * * *'
jobs:
  Checkout-Build-Artifact:

    runs-on: windows-2022

# Checkout-Build-Artifact

    steps:
    - uses: actions/checkout@v3

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Run msbuild
      run: |
          msbuild Verademo-dotnet.sln  
      
    - name: List folder contents for visual of folder contents
      run: |
         dir
         zip VeraDemo-DotNet-App-Artifact.zip Verademo-Dotnet/bin/
  
# Running Software Composition Analysis Agent against the local repo while on a Windows machine since this is ASPDotNet

    - name: SCA Agent Scan of Repo
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
          Set-ExecutionPolicy AllSigned -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
          srcclr scan --allow-dirty

    - name: Veracode Upload and Scan Action Step
      uses: veracode/veracode-uploadandscan-action@master
      id: upload_and_scan
      with:
        appname: 'VeraDemo-DotNet-GitHub'
        createprofile: false
        version: '${{ github.run_id }}'
        criticality: Medium
        filepath: 'VeraDemo-DotNet-App-Artifact.zip'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
      continue-on-error: true
